version: '3.1'

services:

  frontend:
    build:
      context: ../
      dockerfile: ./docker/images/Dockerfile.frontend
    ports:
      - "8080:80"

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - /db:/pb_data
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
